Created README.md
intelagense/howdy pull request #4
Opened 2024-06-25 04:00 UTC by scorp-jzp

The basics for the README.md are here! I worked with the stuff we had, so most things are TBD yet. 
The file will be changed as the project is updated, and we can also add more screenshots/images (for instructions and stuff).

2024-06-26 22:36 UTC, DaPandamonium commented
@scorp-jzp maybe add also a structure example? For example one of my README.md:

## File Structure

```
sanctuary-bot/
│
├── bot.py
├── bluetracker.py
├── join_role.py
├── archive.py
├── requirements.txt
├── .env
├── last_pings.json
├── upcoming_boss_events.json
├── total_archived.json
├── pinned_threads.json
└── README.md
```

2024-06-27 04:42 UTC, intelagense commented
Great idea @DaPandamonium 

Here is a useful tool I had bookmarked for that 😆 
https://tree.nathanfriend.io/

@scorp-jzp we don't have a file structure yet, but do you want to add a placeholder file structure with a title ?

2024-06-27 05:12 UTC, wgcv requested changes

2024-06-27 05:12 UTC, wgcv commented on README.md
> +TBD
We should add `git clone git@github.com:intelagense/howdy.git`

2024-06-27 05:12 UTC, wgcv commented on header-howdy.png
I love the header!
We should put this in a folder, something like `/assets` or create a branch with and call the images from`/doc/img`?

2024-06-27 05:12 UTC, wgcv commented on README.md
> +TBD
Solved

2024-06-27 05:12 UTC, merged

2024-06-27 05:14 UTC, intelagense commented on header-howdy.png
➕ 1
We will probably refactor this when we get a file structure built. 👍

2024-06-27 05:20 UTC, intelagense commented
@scorp-jzp 🙌 Thanks!